const copy = {
  zh: {
    available: '欢迎交流有思考的工作', profileCopy: 'AI 产品经理、Agent workflow builder 与城市计算研究者。把复杂的技术能力，变成可以被使用、观察和持续迭代的工作流。', kicker: 'AI 产品 · Agent 系统 · 城市智能', heroLead: '我在产品、软件和城市研究的交界处工作，关注如何让智能系统真正进入日常工作现场。', educationTitle: '教育背景', nju: '数字建筑与 CAAD · 硕士研究生 · 推免', rankNju: 'Rank 2 / 7 · 南京大学城市 AI 与绿色人居营造省重点实验室', hfut: '本科 · 建筑 / 城市与计算方向', experienceTitle: '实习经历', internRole: 'AI 产品经理实习生', internIntro: '面向军工大模型垂直应用，负责企业 AI 能力中台与多智能体协作 IDE 的产品设计、原型验证和核心流程落地。', aibaseTitle: '企业 AI 能力中台', aibaseBody: '设计个人资产与市场资产双库，建立 Skills / MCP Tools 的创建、发布、撤回与只读复用规则，并落地“消息 → 工具调用 → 观测 → 完成”的 ReAct 执行闭环。', ideTitle: '多智能体协作筹划 IDE', ideBody: '负责 Skill Creator 全流程、思维链认知协作画布和过程留痕，让领域 SOP 能沉淀为可版本化的 Agent 技能资产。', projectsTitle: '项目经历', zyncSubtitle: '面向多 Agent 并行开发的桌面编排与治理工作台', zyncBody: '我参与产品设计与前端核心功能开发，把多个 Claude Code / Codex CLI 工作位组织成可切换、可观察、可恢复的 tmux-like 工作流。', researchTitle: '科研', researchIntro: '我的研究关注城市形态、空间关系与图学习之间的连接，尝试把不完整的城市证据转化为可分析、可解释的空间知识。', paperOne: '提出 Morpho-GNN，在空间邻接与形态相似性的联合图结构中重建缺失的街区形态证据，为城市更新单元划定提供连续的空间依据。', paperTwo: '构建双通道 Morph-GNN，同时编码空间邻接和形态相似性，在南京 4,364 个街区上生成连续且内部一致的城市形态区域。', paperThree: '建立建筑—外部空间异质图数据模型，将形态证据与空间关系连接起来，支持历史街区的保护优先与低干预更新判断。'
  },
  en: {
    available: 'Available for thoughtful work', profileCopy: 'AI product manager, agent workflow builder, and urban computing researcher. I turn complex technical capabilities into workflows people can use, observe, and improve.', kicker: 'AI product · agent systems · urban intelligence', heroLead: 'I work at the intersection of product, software, and urban research, making intelligent systems useful in the places where work actually happens.', educationTitle: 'Education', nju: 'Digital Architecture & CAAD · Master\'s candidate · Recommended admission', rankNju: 'Rank 2 / 7 · Provincial Key Laboratory of Urban AI & Green Habitat', hfut: 'Undergraduate · Architecture, urbanism & computation', experienceTitle: 'Experience', internRole: 'AI Product Manager Intern', internIntro: 'Working on vertical applications of large models for the defence industry, covering enterprise AI infrastructure and a multi-agent collaboration IDE.', aibaseTitle: 'AIBase · Enterprise AI platform', aibaseBody: 'Designed dual personal and marketplace asset libraries, governance rules for Skills and MCP Tools, and the ReAct loop from message to tool call, observation, and completion.', ideTitle: 'Multi-agent collaboration IDE', ideBody: 'Led the Skill Creator flow, reasoning-collaboration canvas, and traceability layer that turn domain SOPs into versioned agent skills.', projectsTitle: 'Projects', zyncSubtitle: 'A desktop orchestration and governance workspace for parallel agent development', zyncBody: 'Product and frontend contributor to a tmux-like workflow that makes Claude Code and Codex CLI workspaces easy to switch, observe, and recover.', researchTitle: 'Research', researchIntro: 'My research connects urban morphology, spatial relationships, and graph learning to turn incomplete urban evidence into analyzable and interpretable spatial knowledge.', paperOne: 'Morpho-GNN reconstructs missing block-level morphological evidence through a joint graph of spatial adjacency and morphological similarity, supporting urban renewal-unit delineation.', paperTwo: 'A dual-channel Morph-GNN jointly models spatial adjacency and morphological similarity to produce contiguous, internally coherent urban-form regions from 4,364 blocks in Nanjing.', paperThree: 'A heterogeneous building–external-space graph model connects morphological evidence with spatial relationships to support preservation-first, low-intervention decisions in historic districts.'
  }
};
let language = 'zh';
const toggle = document.querySelector('#languageToggle');
function setLanguage(next) { language = next; document.documentElement.lang = next === 'zh' ? 'zh-CN' : 'en'; document.querySelectorAll('[data-i18n]').forEach((node) => { const value = copy[next][node.dataset.i18n]; if (value) node.textContent = value; }); toggle.querySelectorAll('span')[0].classList.toggle('active', next === 'zh'); toggle.querySelectorAll('span')[2].classList.toggle('active', next === 'en'); }
toggle.addEventListener('click', () => setLanguage(language === 'zh' ? 'en' : 'zh'));
setLanguage('zh');
